# Generated by Django 3.2.16 on 2023-11-29 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20231129_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddCommit',
            new_name='AddComment',
        ),
    ]
