# Generated by Django 3.2.16 on 2023-11-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_addcommit_addcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcomment',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
    ]
