# Generated by Django 3.2.16 on 2023-11-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_addcomment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcomment',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images', verbose_name='Фото'),
        ),
    ]
