# Generated by Django 3.2.16 on 2023-11-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20231130_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcomment',
            old_name='birthday',
            new_name='post',
        ),
    ]
